name: Auto-Create PR

on:
  push:
    branches-ignore:
      - 'main' # or your default branch

jobs:
  auto-create-pr:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.ref }}
        fetch-depth: 0 # Fetch all history

    - name: Debug repository info
      run: |
        git remote show origin
        git branch -avv

    - name: Create pull request
      id: create_pr
      uses: peter-evans/create-pull-request@v3
      with:
        title: '${{ github.event.ref }}'
        body: 'Automatically merging branch ${{ github.event.ref }}'
        branch: '${{ github.event.ref }}'
        commit-message: '${{ github.event.ref }}'
        base: 'main' # or your default branch

    - name: Check if pull request was created
      if: ${{ steps.create_pr.outputs.pull-request-number }}
      run: echo "Created pull request" #${{ steps.create_pr.outputs.pull-request-number }}"
