name: Auto-Merge New Branches

on:
  push:
    branches-ignore:
      - 'main' # or your default branch

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Auto-merge pull request
        uses: peter-evans/auto-merge@v2.5.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          merge-method: squash
          delete-branch: true
