name: Auto-Merge New Branches

on:
  push:
    branches-ignore:
      - 'main' # or your default branch

jobs:
  automerge-new-branches:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.ref }}
        fetch-depth: 0 # Fetch all history

    - name: Debug repository info
      run: |
        git remote show origin
        git branch -avv

    - name: Create pull request
      id: create_pr
      uses: peter-evans/create-pull-request@v3
      with:
        title: 'Automerge: ${{ github.event.ref }}'
        body: 'Automatically merging branch ${{ github.event.ref }}'
        branch: '${{ github.event.ref }}'
        commit-message: 'Automerge ${{ github.event.ref }}'
        base: 'main' # or your default branch

    - name: Check if pull request was created
      if: ${{ steps.create_pr.outputs.pull-request-number }}
      run: echo "Created pull request" #${{ steps.create_pr.outputs.pull-request-number }}"

    - name: Merge pull request
      if: ${{ steps.create_pr.outputs.pull-request-number }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PULL_REQUEST_NUMBER: ${{ steps.create_pr.outputs.pull-request-number }}
      run: |
        echo "Merging pull request #${PULL_REQUEST_NUMBER}"
        gh pr merge -s merge -m "Automerge" "${PULL_REQUEST_NUMBER}" || echo "Already merged or closed"
